//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Immigration_Website.Content.Texts.ContentHome {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContentHome {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContentHome() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Immigration_Website.Content.Texts.ContentHome.ContentHome", typeof(ContentHome).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Services.
        /// </summary>
        public static string blackBar_FeaturedServices {
            get {
                return ResourceManager.GetString("blackBar_FeaturedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Information.
        /// </summary>
        public static string blackBar_MoreInformation {
            get {
                return ResourceManager.GetString("blackBar_MoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Services.
        /// </summary>
        public static string blackBar_MoreServices {
            get {
                return ResourceManager.GetString("blackBar_MoreServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string browserTitle {
            get {
                return ResourceManager.GetString("browserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27.
        /// </summary>
        public static string counter_1_Number {
            get {
                return ResourceManager.GetString("counter_1_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of people living in California between 2011 and 2015 were foreign-born..
        /// </summary>
        public static string counter_1_Text {
            get {
                return ResourceManager.GetString("counter_1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;unit&quot;&gt;%&lt;/span&gt;.
        /// </summary>
        public static string counter_1_Unit {
            get {
                return ResourceManager.GetString("counter_1_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 715.
        /// </summary>
        public static string counter_2_Number {
            get {
                return ResourceManager.GetString("counter_2_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dollars contributed by immigrants to the state’s Gross Domestic Product..
        /// </summary>
        public static string counter_2_Text {
            get {
                return ResourceManager.GetString("counter_2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;unit&quot; style=&quot;font-size:.5em;&quot;&gt;billion&lt;/span&gt;.
        /// </summary>
        public static string counter_2_Unit {
            get {
                return ResourceManager.GetString("counter_2_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 36.
        /// </summary>
        public static string counter_3_Number {
            get {
                return ResourceManager.GetString("counter_3_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of the state’s small business owners are represented by immigrants..
        /// </summary>
        public static string counter_3_Text {
            get {
                return ResourceManager.GetString("counter_3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;unit&quot;&gt;%&lt;/span&gt;.
        /// </summary>
        public static string counter_3_Unit {
            get {
                return ResourceManager.GetString("counter_3_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.6.
        /// </summary>
        public static string counter_4_Number {
            get {
                return ResourceManager.GetString("counter_4_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to immigrants in California became naturalized American citizens between 2004 and 2014..
        /// </summary>
        public static string counter_4_Text {
            get {
                return ResourceManager.GetString("counter_4_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;unit&quot; style=&quot;font-size:.5em;&quot;&gt;million&lt;/span&gt;.
        /// </summary>
        public static string counter_4_Unit {
            get {
                return ResourceManager.GetString("counter_4_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string greenBox_Education {
            get {
                return ResourceManager.GetString("greenBox_Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Jobs &amp; Training.
        /// </summary>
        public static string greenBox_FindJobsAndTraining {
            get {
                return ResourceManager.GetString("greenBox_FindJobsAndTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immigration Services &amp; Citizenship.
        /// </summary>
        public static string greenBox_ImmigrationServicesAndCitizenship {
            get {
                return ResourceManager.GetString("greenBox_ImmigrationServicesAndCitizenship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs &amp; Entrepreneurship.
        /// </summary>
        public static string greenBox_JobsAndEntrepreneurship {
            get {
                return ResourceManager.GetString("greenBox_JobsAndEntrepreneurship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn English.
        /// </summary>
        public static string greenBox_LearnEnglish {
            get {
                return ResourceManager.GetString("greenBox_LearnEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Help &amp; Citizenship.
        /// </summary>
        public static string greenBox_LegalHelpAndCitizenship {
            get {
                return ResourceManager.GetString("greenBox_LegalHelpAndCitizenship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Benefits.
        /// </summary>
        public static string greenBox_PublicBenefits {
            get {
                return ResourceManager.GetString("greenBox_PublicBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1 id=&quot;welcome&quot; style=&quot;text-align: center; color: azure; &quot;&gt;Welcome to California&lt;/h1&gt;.
        /// </summary>
        public static string greenBox_WelcomeToCalifornia {
            get {
                return ResourceManager.GetString("greenBox_WelcomeToCalifornia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department of Justice&lt;br /&gt;Office of Immigration Assistance.
        /// </summary>
        public static string resource_1_Text {
            get {
                return ResourceManager.GetString("resource_1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA Courts&lt;br /&gt;Immigration Legal Help.
        /// </summary>
        public static string resource_2_Text {
            get {
                return ResourceManager.GetString("resource_2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA Courts&lt;br /&gt;Families and Children.
        /// </summary>
        public static string resource_3_Text {
            get {
                return ResourceManager.GetString("resource_3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA Courts&lt;br /&gt;Immigration Basic Information.
        /// </summary>
        public static string resource_4_Text {
            get {
                return ResourceManager.GetString("resource_4_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Resources.
        /// </summary>
        public static string resources_Title {
            get {
                return ResourceManager.GetString("resources_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to California is home to many newcomers from all over the world.  In an effort to integrate immigrants, California has developed innovative services that help immigrants become part of the social, economic and civic fabric of our state.  This guide features services that help immigrants thrive and succeed in their paths towards integration.  Immigrants seeking help with English language learning, workforce skill development, naturalization preparation or legal assistance, can find information on available serv [rest of string was truncated]&quot;;.
        /// </summary>
        public static string welcome_Text {
            get {
                return ResourceManager.GetString("welcome_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Immigrant Guide.
        /// </summary>
        public static string welcome_Title {
            get {
                return ResourceManager.GetString("welcome_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Know your rights.
        /// </summary>
        public static string yellowBar_KnowRights {
            get {
                return ResourceManager.GetString("yellowBar_KnowRights", resourceCulture);
            }
        }
    }
}
