//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Immigration_Website.Content.Texts.YourRights {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class YourRights {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal YourRights() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Immigration_Website.Content.Texts.YourRights.YourRights", typeof(YourRights).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Know Your Rights.
        /// </summary>
        public static string browserTitle {
            get {
                return ResourceManager.GetString("browserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;All Californians, regardless of immigration status, have protections under our laws and Constitution.&lt;/p&gt;
        ///&lt;ul&gt;
        ///            &lt;li&gt;&lt;a href=&quot;https://www.nilc.org/issues/immigration-enforcement/everyone-has-certain-basic-rights/&quot;&gt;Know Your Basic Rights&lt;/a&gt;&lt;/li&gt;
        ///            &lt;li&gt;&lt;a href=&quot;https://www.ilrc.org/step-step-family-preparedness-plan&quot;&gt;Prepare a family preparedness plan&lt;/a&gt;&lt;/li&gt;
        ///            &lt;li&gt;Know Your Rights at Work ( &lt;a href=&quot;https://legalaidatwork.org/factsheet/workplace-raids-workers-rights/&quot;&gt;E [rest of string was truncated]&quot;;.
        /// </summary>
        public static string pageText {
            get {
                return ResourceManager.GetString("pageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Know Your Rights.
        /// </summary>
        public static string pageTitle {
            get {
                return ResourceManager.GetString("pageTitle", resourceCulture);
            }
        }
    }
}
