//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Immigration_Website.Content.Texts.LearnEnglish {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Immigration_Website.Content.Texts.LearnEnglish.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Learn English Resources.
        /// </summary>
        public static string pageAdditionalResoucesHeader {
            get {
                return ResourceManager.GetString("pageAdditionalResoucesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;group&quot;&gt;
        ///            &lt;div class=&quot;half&quot;&gt;
        ///                &lt;div class=&quot;media&quot;&gt;
        ///                    &lt;div class=&quot;media-body&quot;&gt;
        ///                        &lt;ul class=&quot;list-standout&quot;&gt;
        ///                            &lt;li&gt;
        ///                                &lt;a href=&quot;http://www.usalearns.org/&quot; target=&quot;_blank&quot;&gt;&lt;strong&gt;U.S.A. Learns&lt;/strong&gt;&lt;/a&gt;
        ///                                &lt;p&gt;U.S.A. Learns is a free website for adults to learn English.  On this website you can practice English speaking, reading, writing, list [rest of string was truncated]&quot;;.
        /// </summary>
        public static string pageAdditionalResoucesLinks {
            get {
                return ResourceManager.GetString("pageAdditionalResoucesLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn English &amp;mdash; State Agencies.
        /// </summary>
        public static string pageFirstAgenciesSectionHeader {
            get {
                return ResourceManager.GetString("pageFirstAgenciesSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn English &amp;mdash; Services.
        /// </summary>
        public static string pageFirstServicesSectionHeader {
            get {
                return ResourceManager.GetString("pageFirstServicesSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;font-size: 1.2em;&quot;&gt;California has classes and services to help people learn English. These classes and services are offered by adult education programs across the state. You can find these programs at schools, community colleges, public libraries, and community based organizations. Learning English can help you continue your education and earn a high school diploma and college degree. &lt;/p&gt;.
        /// </summary>
        public static string pageIntroText {
            get {
                return ResourceManager.GetString("pageIntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string pageSecondAgenciesSectionHeader {
            get {
                return ResourceManager.GetString("pageSecondAgenciesSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string pageSecondServicesSectionHeader {
            get {
                return ResourceManager.GetString("pageSecondServicesSectionHeader", resourceCulture);
            }
        }
    }
}
