//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Immigration_Website.Content.Texts.DisasterRelief {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisasterRelief {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisasterRelief() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Immigration_Website.Content.Texts.DisasterRelief.DisasterRelief", typeof(DisasterRelief).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WILDFIRE, FLOOD, AND MUDSLIDE RECOVERY RESOURCES.
        /// </summary>
        public static string browserTitle {
            get {
                return ResourceManager.GetString("browserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;text-align:center;font-weight:bold;font-size: 1.6em&quot; role=&quot;heading&quot; aria-level=&quot;1&quot;&gt;WILDFIRE, FLOOD, AND MUDSLIDE RECOVERY RESOURCES&lt;/p&gt;
        ///
        ///&lt;p&gt;Below you will find links to disaster recovery resources and information on ensuring your health and safety.&lt;/p&gt;
        ///
        ///&lt;p style=&quot;font-weight:bold;font-size: 1.2em&quot;&gt;Disaster Relief for Immigrants Guide&lt;/p&gt;
        ///
        ///&lt;p&gt;The California Department of Social Services Guide to Disaster Services for Immigrant Californians provides detailed information about the different typ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string pageText {
            get {
                return ResourceManager.GetString("pageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WILDFIRE, FLOOD, AND MUDSLIDE RECOVERY RESOURCES.
        /// </summary>
        public static string pageTitle {
            get {
                return ResourceManager.GetString("pageTitle", resourceCulture);
            }
        }
    }
}
