//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Immigration_Website.Content.Texts.MultiPage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MultiPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MultiPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Immigration_Website.Content.Texts.MultiPage.MultiPage", typeof(MultiPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string bottom_Copyright {
            get {
                return ResourceManager.GetString("bottom_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State of California.
        /// </summary>
        public static string bottom_StateOfCa {
            get {
                return ResourceManager.GetString("bottom_StateOfCa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility.
        /// </summary>
        public static string footer_Accessibility {
            get {
                return ResourceManager.GetString("footer_Accessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Top.
        /// </summary>
        public static string footer_BackToTop {
            get {
                return ResourceManager.GetString("footer_BackToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions of Use.
        /// </summary>
        public static string footer_ConditionsOfUse {
            get {
                return ResourceManager.GetString("footer_ConditionsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string footer_PrivacyPolicy {
            get {
                return ResourceManager.GetString("footer_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.S. Citizen Voter Registration.
        /// </summary>
        public static string footer_VoterRegistration {
            get {
                return ResourceManager.GetString("footer_VoterRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Services.
        /// </summary>
        public static string header_AdditionalServices {
            get {
                return ResourceManager.GetString("header_AdditionalServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string header_Language {
            get {
                return ResourceManager.GetString("header_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string header_Settings {
            get {
                return ResourceManager.GetString("header_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Agencies.
        /// </summary>
        public static string header_StateAgencies {
            get {
                return ResourceManager.GetString("header_StateAgencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string nav_Education {
            get {
                return ResourceManager.GetString("nav_Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Jobs &amp; Training.
        /// </summary>
        public static string nav_FindJobsAndTraining {
            get {
                return ResourceManager.GetString("nav_FindJobsAndTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string nav_Home {
            get {
                return ResourceManager.GetString("nav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immigration Services &amp; Citizenship.
        /// </summary>
        public static string nav_ImmigrationServicesAndCitizenship {
            get {
                return ResourceManager.GetString("nav_ImmigrationServicesAndCitizenship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs &amp; Entrepreneurship.
        /// </summary>
        public static string nav_JobsAndEntrepreneurship {
            get {
                return ResourceManager.GetString("nav_JobsAndEntrepreneurship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn English.
        /// </summary>
        public static string nav_LearnEnglish {
            get {
                return ResourceManager.GetString("nav_LearnEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Help &amp; Citizenship.
        /// </summary>
        public static string nav_LegalHelpAndCitizenship {
            get {
                return ResourceManager.GetString("nav_LegalHelpAndCitizenship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Benefits.
        /// </summary>
        public static string nav_PublicBenefits {
            get {
                return ResourceManager.GetString("nav_PublicBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string nav_Search {
            get {
                return ResourceManager.GetString("nav_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to California Immigrant Guide.
        /// </summary>
        public static string page_SiteName {
            get {
                return ResourceManager.GetString("page_SiteName", resourceCulture);
            }
        }
    }
}
