//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Immigration_Website.Content.Texts.MultiPage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OLD______Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OLD______Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Immigration_Website.Content.Texts.MultiPage.OLD______Content", typeof(OLD______Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Education Resources.
        /// </summary>
        public static string pageAdditionalResoucesHeader {
            get {
                return ResourceManager.GetString("pageAdditionalResoucesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;group&quot;&gt;
        ///            &lt;div class=&quot;half&quot;&gt;
        ///                &lt;div class=&quot;media&quot;&gt;
        ///                    &lt;!-- &lt;div class=&quot;media-left&quot;&gt;&lt;span class=&quot;ca-gov-icon-capitol text-accent1 biggest&quot;&gt;&lt;/span&gt;&lt;/div&gt; --&gt;
        ///                    &lt;div class=&quot;media-body&quot;&gt;
        ///
        ///                        &lt;ul class=&quot;list-standout&quot;&gt;
        ///                            &lt;li&gt;
        ///                                &lt;a href=&quot;https://dream.csac.ca.gov/&quot; target=&quot;_blank&quot;&gt;&lt;strong&gt;California Dream Act&lt;/strong&gt;&lt;/a&gt;
        ///                                &lt;p&gt;Th [rest of string was truncated]&quot;;.
        /// </summary>
        public static string pageAdditionalResoucesLinks {
            get {
                return ResourceManager.GetString("pageAdditionalResoucesLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education  &amp;mdash; State Agencies.
        /// </summary>
        public static string pageFirstAgenciesSectionHeader {
            get {
                return ResourceManager.GetString("pageFirstAgenciesSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education  &amp;mdash; Services.
        /// </summary>
        public static string pageFirstServicesSectionHeader {
            get {
                return ResourceManager.GetString("pageFirstServicesSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;font-size: 1.2em;&quot;&gt;
        ///            California has schools for people of all ages and skill levels. There are public and private elementary, middle, and high schools. There are also private colleges and universities. Our state public colleges include the &lt;a href=&quot;https://www.universityofcalifornia.edu/&quot; target=&quot;_blank&quot;&gt;University of California (UC)&lt;/a&gt;, &lt;a href=&quot;https://www2.calstate.edu/&quot; target=&quot;_blank&quot;&gt;California State University (CSU)&lt;/a&gt;, and &lt;a href=&quot;http://www.cccco.edu/&quot; target=&quot;_blank&quot;&gt;Calif [rest of string was truncated]&quot;;.
        /// </summary>
        public static string pageIntroText {
            get {
                return ResourceManager.GetString("pageIntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string pageSecondAgenciesSectionHeader {
            get {
                return ResourceManager.GetString("pageSecondAgenciesSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string pageSecondServicesSectionHeader {
            get {
                return ResourceManager.GetString("pageSecondServicesSectionHeader", resourceCulture);
            }
        }
    }
}
